output "ssl_key" {
value       = acme_certificate.certificate.private_key_pem
description = "the private key generated by the acme cert"
}

output "ssl_cert" {
value       = acme_certificate.certificate.certificate_pem
description = "the acme cert"
}
